-- R1-A post-migration structural/security verification. READ ONLY.
DO $$
DECLARE expected text[] := ARRAY['obras','obra_versiones','montajes','montaje_secciones','montaje_filas','montaje_alumnos','obra_compases','montaje_compases','catalogo_estados_preparacion','montaje_alumno_compases','montaje_pasajes','montaje_pasaje_compases','montaje_grupos_compases','montaje_grupo_compases','sesion_repertorio_trabajos','sesion_repertorio_trabajo_compases','observacion_sesion_repertorio','montaje_preparacion_historial','montaje_targets','montaje_target_milestones','montaje_eventos','repertoire_signals','repertoire_signal_deliveries','montaje_fila_maestros']; n text; missing text[];
BEGIN
  SELECT array_agg(x.n) INTO missing FROM unnest(expected) AS x(n) WHERE to_regclass('public.' || x.n) IS NULL;
  IF missing IS NOT NULL THEN RAISE EXCEPTION 'missing Repertoire tables: %', missing; END IF;
  IF EXISTS (SELECT 1 FROM unnest(expected) AS x(n) WHERE NOT (SELECT relrowsecurity FROM pg_class WHERE oid=('public.' || x.n)::regclass)) THEN RAISE EXCEPTION 'RLS missing on Repertoire table'; END IF;
  IF to_regprocedure('public.fn_repertoire_update_preparation(uuid,uuid,public.estado_preparacion,uuid,text,text,uuid,uuid,uuid,uuid)') IS NULL OR to_regprocedure('public.fn_repertoire_update_applicability(uuid,uuid,public.aplicabilidad_compas,uuid)') IS NULL THEN RAISE EXCEPTION 'required RPC missing'; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.montaje_eventos'::regclass AND confrelid='public.calendario_institucional'::regclass) THEN RAISE EXCEPTION 'montaje_eventos must reference calendario_institucional'; END IF;
  IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.montaje_eventos'::regclass AND confrelid::regclass::text IN ('public.eventos_conciertos','public.soi_eventos')) THEN RAISE EXCEPTION 'forbidden concert dependency exists'; END IF;
  IF NOT has_table_privilege('authenticated','public.montaje_compases','SELECT') OR has_table_privilege('authenticated','public.montaje_compases','UPDATE') THEN RAISE EXCEPTION 'preparation table grants differ from contract'; END IF;
  IF has_table_privilege('authenticated','public.montaje_preparacion_historial','INSERT') OR has_table_privilege('authenticated','public.montaje_preparacion_historial','UPDATE') OR has_table_privilege('authenticated','public.montaje_preparacion_historial','DELETE') THEN RAISE EXCEPTION 'history direct write grant exists'; END IF;
  IF has_function_privilege('public','public.fn_repertoire_update_preparation(uuid,uuid,public.estado_preparacion,uuid,text,text,uuid,uuid,uuid,uuid)','EXECUTE') OR NOT has_function_privilege('authenticated','public.fn_repertoire_update_preparation(uuid,uuid,public.estado_preparacion,uuid,text,text,uuid,uuid,uuid,uuid)','EXECUTE') THEN RAISE EXCEPTION 'preparation RPC grants differ from contract'; END IF;
  IF has_function_privilege('public','public.fn_repertoire_update_applicability(uuid,uuid,public.aplicabilidad_compas,uuid)','EXECUTE') OR NOT has_function_privilege('authenticated','public.fn_repertoire_update_applicability(uuid,uuid,public.aplicabilidad_compas,uuid)','EXECUTE') THEN RAISE EXCEPTION 'applicability RPC grants differ from contract'; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policy WHERE polrelid='public.montaje_fila_maestros'::regclass AND polname IN ('repertoire_fila_assignment_read','repertoire_fila_assignment_manage')) THEN RAISE EXCEPTION 'assignment RLS contract missing'; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policy WHERE polrelid='public.repertoire_signals'::regclass AND polname='repertoire_signals_recipient_read') THEN RAISE EXCEPTION 'signal recipient RLS contract missing'; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policy WHERE polrelid='public.montaje_targets'::regclass AND polname='repertoire_targets_write_scope') THEN RAISE EXCEPTION 'target scope RLS contract missing'; END IF;
  RAISE NOTICE 'R1-A structural and security verification passed';
END $$;
