server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Desactivar logs innecesarios para favicon y robots
    location = /favicon.ico { 
        log_not_found off; 
        access_log off; 
    }
    location = /robots.txt  { 
        log_not_found off; 
        access_log off; 
    }

    # Caché estricto de recursos estáticos para performance en VPS
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|otf)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    # Compresión gzip para descargas ultrarrápidas
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Páginas de error estándar
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}