import { config } from "../../../core/config/config.js"
import * as supabaseImpl from "./inventarioSupabase.js"
import * as mockImpl from "./inventarioMock.js"

const getApi = () => (config.isDemoMode ? mockImpl : supabaseImpl)

export const obtenerActivos = (...args) => getApi().obtenerActivos(...args)
export const crearActivo = (...args) => getApi().crearActivo(...args)
export const actualizarActivo = (...args) => getApi().actualizarActivo(...args)
export const obtenerActivoPorId = (...args) => getApi().obtenerActivoPorId(...args)
export const cambiarEstadoActivo = (...args) => getApi().cambiarEstadoActivo(...args)
export const subirFotoActivo = (...args) => getApi().subirFotoActivo(...args)
export const obtenerAccesorios = (...args) => getApi().obtenerAccesorios(...args)
export const crearAccesorio = (...args) => getApi().crearAccesorio(...args)
export const actualizarAccesorio = (...args) => getApi().actualizarAccesorio(...args)
export const eliminarAccesorio = (...args) => getApi().eliminarAccesorio(...args)
export const obtenerHistorialActivo = (...args) => getApi().obtenerHistorialActivo(...args)
export const crearEventoManual = (...args) => getApi().crearEventoManual(...args)
export const obtenerReparaciones = (...args) => getApi().obtenerReparaciones(...args)
export const obtenerReparacion = (...args) => getApi().obtenerReparacion(...args)
export const crearReparacion = (...args) => getApi().crearReparacion(...args)
export const actualizarReparacion = (...args) => getApi().actualizarReparacion(...args)
export const cambiarEstadoReparacion = (...args) => getApi().cambiarEstadoReparacion(...args)
export const eliminarReparacion = (...args) => getApi().eliminarReparacion(...args)
export const obtenerFacturasReparacion = (...args) => getApi().obtenerFacturasReparacion(...args)
export const obtenerFactura = (...args) => getApi().obtenerFactura(...args)
export const crearFacturaReparacion = (...args) => getApi().crearFacturaReparacion(...args)
export const registrarPagoFactura = (...args) => getApi().registrarPagoFactura(...args)
export const anularFactura = (...args) => getApi().anularFactura(...args)
export const obtenerComodatosVencidos = (...args) => getApi().obtenerComodatosVencidos(...args)
export const obtenerComodatosPorVencer = (...args) => getApi().obtenerComodatosPorVencer(...args)
export const intercambiarInstrumentos = (...args) => getApi().intercambiarInstrumentos(...args)
export const renovarComodato = (...args) => getApi().renovarComodato(...args)
export const generarContratoPDF = (...args) => getApi().generarContratoPDF(...args)
export const generarReporte = (...args) => getApi().generarReporte(...args)
export const obtenerKPI = (...args) => getApi().obtenerKPI(...args)
export const crearComodato = (...args) => getApi().crearComodato(...args)
export const devolverComodato = (...args) => getApi().devolverComodato(...args)
export const obtenerComodatosAlumno = (...args) => getApi().obtenerComodatosAlumno(...args)
export const obtenerComodatosActivos = (...args) => getApi().obtenerComodatosActivos(...args)
export const obtenerActivosOciosos = (...args) => getApi().obtenerActivosOciosos(...args)
export const subirContratoComodato = (...args) => getApi().subirContratoComodato(...args)