/**
 * AUTO-GENERATED TEMPLATE FROM OPENPENCIL DESIGN
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Source: login_view.op
 */

export const templateHtml = `<div class="op-frame-frame-login-screen">
      <div class="op-rect-rect-branding-side"></div>
      <div class="op-text-text-branding-logo">🎵</div>
      <div class="op-text-text-branding-title">Portal de Maestros</div>
      <div class="op-text-text-branding-subtitle">by SOI - El Sistema Punta Cana</div>
      <div class="op-rect-rect-form-side"></div>
      <div class="op-rect-rect-login-card"></div>
      <div class="op-text-text-card-title">Iniciar Sesión</div>
      <div class="op-group-group-input-email">
      <div class="op-text-text-label-email">CORREO ELECTRÓNICO</div>
      <input class="op-rect-rect-input-email pm-input" id="pm-email" type="email" placeholder="tu@correo.com" /></div>
      <div class="op-group-group-input-password">
      <div class="op-text-text-label-password">CONTRASEÑA</div>
      <input class="op-rect-rect-input-password pm-input" id="pm-password" type="password" placeholder="••••••••" />
      <button class="op-rect-rect-btn-eye pm-password-toggle" id="pm-toggle-password" type="button"><i class="bi bi-eye"></i></button></div>
      <div class="op-group-group-checkboxes">
      <input class="op-rect-rect-chk-remember" id="pm-remember-email" type="checkbox" />
      <div class="op-text-text-lbl-remember">Recordar correo electrónico</div>
      <input class="op-rect-rect-chk-keep" id="pm-keep-session" type="checkbox" />
      <div class="op-text-text-lbl-keep">Mantener sesión activa (30 días)</div></div>
      <button class="op-rect-rect-btn-login pm-btn-primary" id="pm-login-btn" type="button">
          <span class="pm-btn-text">Iniciar sesión</span>
          <span class="pm-btn-loader d-none">
            <span class="pm-spinner-sm"></span>
            Validando...
          </span>
        </button>
      <button class="op-rect-rect-btn-biometric pm-btn-secondary" id="pm-biometric-btn" type="button"><i class="bi bi-fingerprint"></i> Usar huella o Face ID</button>
      <a class="op-text-text-register-link pm-link" id="pm-register-route-link" href="#" data-route="register">¿No tienes cuenta? Regístrate como maestro</a>
      <p class="pm-error-msg" id="pm-login-error" aria-live="polite" style="position:absolute; left:900px; top:690px; width:360px; color:#ef4444; font-size:12px; font-weight:600;"></p>
    </div>`

export const templateCss = `/* Frame: Portal Maestros - Login Screen */
.op-frame-frame-login-screen {
  position: relative;
  width: 100%;
  max-width: 1440px;
  height: 900px;
  background: #0f172a;
  border-radius: 0px;
  overflow: hidden;
  box-shadow: 0 10px 30px rgba(0,0,0,0.25);
  margin: 0 auto;
}

.op-rect-rect-branding-side {
  position: absolute;
  left: 0px;
  top: 0px;
  width: 720px;
  height: 900px;
  background: linear-gradient(135deg, #1e3a8a 0%, #1d4ed8 100%);
  border-radius: 0px;
  
  transition: all 0.2s ease-in-out;
}

.op-text-text-branding-logo {
  position: absolute;
  left: 200px;
  top: 380px;
  width: 80px;
  height: 80px;
  color: #ffffff;
  font-size: 72px;
  font-weight: 700;
  line-height: 1.4;
}

.op-text-text-branding-title {
  position: absolute;
  left: 200px;
  top: 480px;
  width: 400px;
  height: 40px;
  color: #ffffff;
  font-size: 36px;
  font-weight: 800;
  line-height: 1.4;
}

.op-text-text-branding-subtitle {
  position: absolute;
  left: 200px;
  top: 530px;
  width: 400px;
  height: 20px;
  color: rgba(255, 255, 255, 0.7);
  font-size: 14px;
  font-weight: 500;
  line-height: 1.4;
}

.op-rect-rect-form-side {
  position: absolute;
  left: 720px;
  top: 0px;
  width: 720px;
  height: 900px;
  background: #0f172a;
  border-radius: 0px;
  
  transition: all 0.2s ease-in-out;
}

.op-rect-rect-login-card {
  position: absolute;
  left: 860px;
  top: 200px;
  width: 440px;
  height: 500px;
  background: #1e293b;
  border-radius: 24px;
  border: 1px solid rgba(255, 255, 255, 0.05);
  transition: all 0.2s ease-in-out;
}

.op-text-text-card-title {
  position: absolute;
  left: 900px;
  top: 240px;
  width: 360px;
  height: 24px;
  color: #ffffff;
  font-size: 20px;
  font-weight: 800;
  line-height: 1.4;
}

.op-text-text-label-email {
  position: absolute;
  left: 900px;
  top: 290px;
  width: 360px;
  height: 14px;
  color: rgba(255, 255, 255, 0.5);
  font-size: 10px;
  font-weight: 700;
  line-height: 1.4;
}

.op-rect-rect-input-email {
  position: absolute;
  left: 900px;
  top: 312px;
  width: 360px;
  height: 45px;
  background: rgba(255, 255, 255, 0.02);
  border-radius: 12px;
  border: 1px solid rgba(255, 255, 255, 0.1);
  transition: all 0.2s ease-in-out;
}

.op-text-text-label-password {
  position: absolute;
  left: 900px;
  top: 380px;
  width: 360px;
  height: 14px;
  color: rgba(255, 255, 255, 0.5);
  font-size: 10px;
  font-weight: 700;
  line-height: 1.4;
}

.op-rect-rect-input-password {
  position: absolute;
  left: 900px;
  top: 402px;
  width: 360px;
  height: 45px;
  background: rgba(255, 255, 255, 0.02);
  border-radius: 12px;
  border: 1px solid rgba(255, 255, 255, 0.1);
  transition: all 0.2s ease-in-out;
}

.op-rect-rect-btn-eye {
  position: absolute;
  left: 1220px;
  top: 412px;
  width: 26px;
  height: 26px;
  background: rgba(255, 255, 255, 0.05);
  border-radius: 6px;
  
  transition: all 0.2s ease-in-out;
}

.op-rect-rect-chk-remember {
  position: absolute;
  left: 900px;
  top: 472px;
  width: 16px;
  height: 16px;
  background: rgba(255, 255, 255, 0.05);
  border-radius: 4px;
  border: 1px solid rgba(255, 255, 255, 0.2);
  transition: all 0.2s ease-in-out;
}

.op-text-text-lbl-remember {
  position: absolute;
  left: 924px;
  top: 473px;
  width: 240px;
  height: 14px;
  color: #e5e7eb;
  font-size: 11px;
  font-weight: 600;
  line-height: 1.4;
}

.op-rect-rect-chk-keep {
  position: absolute;
  left: 900px;
  top: 502px;
  width: 16px;
  height: 16px;
  background: #3b82f6;
  border-radius: 4px;
  
  transition: all 0.2s ease-in-out;
}

.op-text-text-lbl-keep {
  position: absolute;
  left: 924px;
  top: 503px;
  width: 240px;
  height: 14px;
  color: #e5e7eb;
  font-size: 11px;
  font-weight: 600;
  line-height: 1.4;
}

.op-rect-rect-btn-login {
  position: absolute;
  left: 900px;
  top: 545px;
  width: 360px;
  height: 48px;
  background: #3b82f6;
  border-radius: 12px;
  
  transition: all 0.2s ease-in-out;
}

.op-rect-rect-btn-biometric {
  position: absolute;
  left: 900px;
  top: 605px;
  width: 360px;
  height: 42px;
  background: rgba(255, 255, 255, 0.03);
  border-radius: 12px;
  border: 1px solid rgba(255, 255, 255, 0.1);
  transition: all 0.2s ease-in-out;
}

.op-text-text-register-link {
  position: absolute;
  left: 900px;
  top: 662px;
  width: 360px;
  height: 16px;
  color: #3b82f6;
  font-size: 11px;
  font-weight: 600;
  line-height: 1.4;
}

/* --- Adaptabilidad Responsive (Auto-inyectado) --- */
@media (max-width: 1024px) {
  .op-frame-frame-login-screen {
    display: flex !important;
    flex-direction: column !important;
    justify-content: center !important;
    align-items: center !important;
    height: 100vh !important;
    min-height: 100vh !important;
    background: #0f172a !important;
    padding: 20px !important;
  }
  .op-rect-rect-branding-side,
  .op-rect-rect-form-side {
    display: none !important;
  }
  .op-text-text-branding-logo {
    position: relative !important;
    left: auto !important;
    top: auto !important;
    margin: 0 auto 10px auto !important;
    text-align: center !important;
    width: auto !important;
    height: auto !important;
    font-size: 48px !important;
    display: block !important;
  }
  .op-text-text-branding-title {
    position: relative !important;
    left: auto !important;
    top: auto !important;
    margin: 0 auto 5px auto !important;
    text-align: center !important;
    width: auto !important;
    height: auto !important;
    font-size: 28px !important;
    font-weight: 800 !important;
    display: block !important;
  }
  .op-text-text-branding-subtitle {
    position: relative !important;
    left: auto !important;
    top: auto !important;
    margin: 0 auto 20px auto !important;
    text-align: center !important;
    width: auto !important;
    height: auto !important;
    font-size: 13px !important;
    color: rgba(255, 255, 255, 0.6) !important;
    display: block !important;
  }
  .op-rect-rect-login-card {
    position: relative !important;
    left: auto !important;
    top: auto !important;
    width: 100% !important;
    max-width: 460px !important;
    height: auto !important;
    min-height: auto !important;
    padding: 40px !important;
    margin: 0 auto !important;
    display: flex !important;
    flex-direction: column !important;
    gap: 20px !important;
    box-sizing: border-box !important;
  }
  .op-text-text-card-title {
    position: relative !important;
    left: auto !important;
    top: auto !important;
    width: 100% !important;
    height: auto !important;
    margin-bottom: 5px !important;
  }
  .op-group-group-input-email,
  .op-group-group-input-password {
    position: relative !important;
    left: auto !important;
    top: auto !important;
    width: 100% !important;
    height: auto !important;
    display: flex !important;
    flex-direction: column !important;
    gap: 6px !important;
  }
  .op-text-text-label-email,
  .op-text-text-label-password {
    position: relative !important;
    left: auto !important;
    top: auto !important;
    width: auto !important;
    height: auto !important;
  }
  .op-rect-rect-input-email,
  .op-rect-rect-input-password {
    position: relative !important;
    left: auto !important;
    top: auto !important;
    width: 100% !important;
    height: 45px !important;
    margin: 0 !important;
  }
  .op-rect-rect-btn-eye {
    position: absolute !important;
    right: 12px !important;
    top: 31px !important;
    left: auto !important;
    width: 26px !important;
    height: 26px !important;
  }
  .op-group-group-checkboxes {
    position: relative !important;
    left: auto !important;
    top: auto !important;
    width: 100% !important;
    height: auto !important;
    display: flex !important;
    flex-direction: column !important;
    gap: 12px !important;
    margin: 5px 0 !important;
  }
  .op-rect-rect-chk-remember,
  .op-rect-rect-chk-keep {
    position: relative !important;
    left: auto !important;
    top: auto !important;
    display: inline-block !important;
    margin-right: 8px !important;
    vertical-align: middle !important;
  }
  .op-text-text-lbl-remember,
  .op-text-text-lbl-keep {
    position: relative !important;
    left: auto !important;
    top: auto !important;
    display: inline-block !important;
    width: auto !important;
    height: auto !important;
    vertical-align: middle !important;
  }
  .op-rect-rect-btn-login {
    position: relative !important;
    left: auto !important;
    top: auto !important;
    width: 100% !important;
    height: 48px !important;
    display: flex !important;
    align-items: center !important;
    justify-content: center !important;
    margin-top: 10px !important;
  }
  .op-text-text-btn-login-label {
    display: none !important;
  }
  .op-rect-rect-btn-biometric {
    position: relative !important;
    left: auto !important;
    top: auto !important;
    width: 100% !important;
    height: 42px !important;
    display: flex !important;
    align-items: center !important;
    justify-content: center !important;
  }
  .op-text-text-btn-biometric-label {
    display: none !important;
  }
  .op-text-text-register-link {
    position: relative !important;
    left: auto !important;
    top: auto !important;
    width: 100% !important;
    height: auto !important;
    text-align: center !important;
    margin-top: 5px !important;
  }
  .pm-error-msg {
    position: relative !important;
    left: auto !important;
    top: auto !important;
    width: 100% !important;
    text-align: center !important;
    margin: 5px 0 !important;
  }
}`
