export { registerRoutesMetricas } from './metricas.router.js'
export { metricasService } from './services/metricasService.js'
export { renderDashboardMetricasView } from './views/dashboardMetricasView.js'
export { renderGamificacionNodos } from './components/gamificacionNodos.js'
export { renderIaReporteGeneradorView } from './views/iaReporteGeneradorView.js'
export { renderIaAlertasPredictivas } from './components/iaAlertasPredictivas.js'
export { renderIaResumenSemanal } from './components/iaResumenSemanal.js'
