export * from './api/periodosApi.js'
export * from './api/reporteCierreApi.js'
export * from './api/calendarioLectivoApi.js'
export { renderPeriodosView } from './views/periodosView.js'
export { renderReporteCierreView } from './views/reporteCierreView.js'
export { renderCalendarioLectivoView } from './views/calendarioLectivoView.js'
export { registerRoutesPeriodos } from './periodos.router.js'
