-- ============================================================================
-- Migration: SOI Pattern Analyzer & Weekly AI Intelligence — Phase 4C
-- Timestamp: 20260818000008
-- Project: sistema-academico-pwa (zmhmdvmyeyswunurcyow)
-- Description: Table for storing weekly pattern analysis generated by Groq AI
--              evaluating operational events (soi_eventos) of the past 7 days.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.soi_analisis_semanal (
  id                       uuid          PRIMARY KEY DEFAULT gen_random_uuid(),
  periodo_inicio           timestamptz   NOT NULL,
  periodo_fin              timestamptz   NOT NULL,
  total_eventos_analizados integer       NOT NULL DEFAULT 0,
  resumen_ejecutivo        text          NOT NULL,
  patrones                 jsonb         NOT NULL DEFAULT '[]'::jsonb,
  tendencias               jsonb         NOT NULL DEFAULT '[]'::jsonb,
  recomendaciones          jsonb         NOT NULL DEFAULT '[]'::jsonb,
  score_promedio           numeric(5, 2),
  modelo_usado             text          DEFAULT 'llama-3.3-70b-versatile',
  created_at               timestamptz   NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_soi_analisis_semanal_created
  ON public.soi_analisis_semanal(created_at DESC);

-- Habilitar RLS
ALTER TABLE public.soi_analisis_semanal ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "soi_analisis_semanal_auth_select" ON public.soi_analisis_semanal;
CREATE POLICY "soi_analisis_semanal_auth_select" ON public.soi_analisis_semanal
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "soi_analisis_semanal_service_all" ON public.soi_analisis_semanal;
CREATE POLICY "soi_analisis_semanal_service_all" ON public.soi_analisis_semanal
  FOR ALL TO service_role USING (true) WITH CHECK (true);
